name: 'IFTTT Maker Event Trigger'
description: 'Trigger IFTTT with your custom event and values'
author: 'cixo'
inputs: 
  event:
    description: 'Event name to trigger'
    required: true
    default: 'my_event'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.event }}
